In [76]:
#Import required python module(s)
import numpy as np 
import math

In [73]:
#load data from file
data = np.genfromtxt('iris_multiclass.csv', delimiter=',',skip_header=True)

#Distribute data into train and test sets
X_train = data[:120,[0,1,2,3]]
Y_train = data[:120,5]

X_test = data[-30:,[0,1,2,3]]
Y_test = data[-30:,5]
print(X_train)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.

In [74]:
#Define the required Sigmoid function
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [96]:
#Define the Raw implementation function to set the parameters (theta)

def fit_implementation(X_train, Y_train, learning_rate=0.0001, max_iteration=1000, debug=False):
    #Adding a column of 1's so that the first element of each input is always 1
    #It would be multiplied with theta_0 later
    X_train= np.insert(X_train, 0, values=1, axis=1)
    no_attributes = X_train.shape[1]
    
    #Initialize model parameters theta
    theta = np.zeros((no_attributes,1))
    
    #Run number of iterations
    for icount in range(max_iteration):
        #delta is the quantity that will be added with theta during updating theta
        delta = np.zeros((no_attributes,1))
        totalLogLikelihood = 0
        #Check each data point
        for instance, actualOutput in zip(X_train,Y_train):
            instance=instance.reshape(no_attributes,1)
            dotResult = np.dot(theta.T, instance)            
            predictedValue=sigmoid(dotResult).squeeze()
            #Calculate the derivative value for this data point
            derivativeValue = instance*(actualOutput-predictedValue)
            #Calculate the amount to be added with theta
            delta += learning_rate*derivativeValue
#             if predictedValue==1:
#                 print("instance",instance)
#                 print("dot result",dotResult)
            logLikelihood = actualOutput*np.log(predictedValue)+(1-actualOutput)*np.log(1-predictedValue)
            totalLogLikelihood += logLikelihood
        theta = theta + delta
        #After each 100 iteration, print the status
        if icount%100==0 and debug==True:
            print(icount)
            print(totalLogLikelihood)
            print(theta)
            
    print(totalLogLikelihood)
    print(theta)
    
    return theta


def multiClassFitImplementation(X_train, Y_train):
    #Determine the list unique classes (unique target variable values) 
    #Changes required here
    Unique_Classes = np.unique(Y_train)
    #For each uniqueclass, determine the best classifier/parameter/theta which best separates the class with others
    #You can temporarily modify Y_train data to achieve the target and can call the fit_implementation function
    parameters = dict()
    #Changes required here   
    for classes in (Unique_Classes):
        temp_Y_train = []
        for itr in range(len(Y_train)):
            if Y_train[itr] != classes:
                temp_Y_train.append(0.0)
            else:
                temp_Y_train.append(1.1)
#         print(temp_Y_train)
        parameters[classes] = fit_implementation(X_train, temp_Y_train)
    

    return parameters

10.378601487723103
[[ 0.22847044]
 [ 0.44091318]
 [ 1.23995218]
 [-1.81987437]
 [-0.82854044]]
-70.33546027675919
[[ 0.09826248]
 [ 0.02460187]
 [-0.63717618]
 [ 0.31374286]
 [-0.13328148]]
-27.26219766778988
[[-0.37396398]
 [-0.78009153]
 [-0.84510509]
 [ 1.33644729]
 [ 0.8901122 ]]


In [112]:
#One of the following parameters of the function is now thetas which is a dictionary containing (targetClass,theta) 
#as (key,value) pairs for all target classes
def prediction(X_test, Y_test, thetas):
    #Adding a column of 1's so that the first element of each input is always 1
    #It would be multiplied with theta_0 later
    X_test= np.insert(X_test, 0, values=1, axis=1)
    no_attributes = X_test.shape[1]
    
    correctCount = 0
    totalCount = 0
    
    maxPredictedValue = -10000
    predictedClass = 1.0
    
    #Check each data point
    for instance, actualOutput in zip(X_test,Y_test):
            instance=instance.reshape(no_attributes,1)
            #Determine the maximum predicted value and predictedClass
            #Changes required here
            predictedValue = []
            for classes in parameters:
                dotResult = np.dot(parameters[classes].T, instance)
                predictedValue.append(sigmoid(dotResult).squeeze())
            predictedOutput = predictedValue.index(max(predictedValue))+1
            print(predictedOutput," ", actualOutput)
            if predictedOutput == actualOutput:
                correctCount += 1
            totalCount += 1
    print("Total Correct Count: ",correctCount," Total Wrong Count: ",totalCount-correctCount," Accuracy: ",(correctCount*100)/(totalCount))
    
#             print(maxPredictedValue, predictedClass, actualOutput)
#             if predictedClass == actualOutput:
#                 correctCount += 1
#             totalCount += 1
#     print("Total Correct Count: ",correctCount," Total Wrong Count: ",totalCount-correctCount," Accuracy: ",(correctCount*100)/(totalCount))
 

# Expected Output: 
Total Correct Count:  30  Total Wrong Count:  0  Accuracy:  100.0

In [113]:
#parameters = multiClassFitImplementation(X_train, Y_train)
prediction(X_test, Y_test, parameters)

1   1.0
1   1.0
1   1.0
1   1.0
1   1.0
2   2.0
2   2.0
2   2.0
3   2.0
2   2.0
3   3.0
3   3.0
3   3.0
3   3.0
3   3.0
1   1.0
1   1.0
1   1.0
1   1.0
1   1.0
3   2.0
3   2.0
2   2.0
2   2.0
3   2.0
3   3.0
3   3.0
3   3.0
3   3.0
3   3.0
